name: clinicky
description: Clinics Appointments app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http:
  lottie:
  page_transition:
  flutter_onboarding_slider:
  custom_radio_grouped_button:
  google_fonts: ^4.0.3
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/images/speciality_icons/
